export const useMachines = () => {
  const agriculturalMachines = [
    "Ciągnik rolniczy",
    "Kombajn zbożowy",
    "Siewnik",
    "Pług",
    "Brona",
    "Rozsiewacz nawozów",
    "Opryskiwacz",
    "Kosiarka rotacyjna",
    "Prasa do słomy",
    "Ładowarka teleskopowa",
    "Ładowacz czołowy",
    "Podnośnik",
    "Przyczepa rolnicza",
    "Kultywator",
    "Rozdrabniacz słomy",
    "Maszyna do zbioru ziemniaków",
    "Maszyna do zbioru buraków",
    "Rębak do drewna",
    "Sadzarka do ziemniaków",
    "Kombajn do kukurydzy",
    "Maszyna do zbioru winogron",
    "Maszyna do zbioru jabłek",
    "Maszyna do nabijania słupów",
    "Kosiarka bijakowa",
    "Prasa zwijająca",
    "Mieszalnik pasz",
    "Dojarka mechaniczna",
    "Separator mleka",
    "Maszyna do sortowania warzyw",
    "Szorowarka do ziemniaków",
    "Rębak do gałęzi",
    "Kosiarka do trawy",
    "Maszyna do zbioru marchwi",
    "Piła łańcuchowa",
    "Maszyna do oprysku winnic",
    "Wertykulator",
    "Harwestery leśne",
    "Siewnik do trawy",
    "Maszyna do zbioru fasoli",
    "Rozrzutnik obornika",
    "Talerzówka",
    "Suszarnia do zboża",
    "Maszyna do zbioru truskawek",
    "Maszyna do zbioru ogórków",
    "Kombajn do zbioru rzepaku",
    "Maszyna do pakowania siana",
    "Rozsiewacz kamienia wapniowego",
  ];
  return agriculturalMachines;
};

export default useMachines;
