export const usePopularCrops = () => {
  const popularCrops = [
    "Pszenica",
    "Żyto",
    "Jęczmień",
    "Owies",
    "Pszenżyto",
    "Kukurydza",
    "Ziemniaki",
    "Buraki cukrowe",
    "Rzepak",
    "Marchew",
    "Cebula",
    "Kapusta",
    "Ogórki",
    "Pomidory",
    "Jabłka",
    "Gruszki",
    "Śliwki",
    "Truskawki",
    "Maliny",
    "Czereśnie",
    "Groch",
    "Fasola",
    "Soczewica",
    "Słonecznik",
    "Chmiel",
    "Tytoń",
    "Papryka",
    "Kalafior",
    "Por",
    "Dynia",
    "Borówka amerykańska",
    "Aronia",
    "Pieczarki",
    "Mięta",
    "Lawenda",
    "Szałwia",
    "Lukrecja",
    "Zielona sałata",
    "Szpinak",
    "Brokuły",
    "Brukiew",
    "Cukinia",
    "Koper",
    "Pietruszka",
    "Bób",
  ];
  return popularCrops;
};

export default usePopularCrops;
